version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: serviceexample-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:7-alpine
    container_name: serviceexample-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  nats:
    image: nats:2-alpine
    container_name: serviceexample-nats
    ports:
      - "4222:4222"
      - "8222:8222"

  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: serviceexample-app
    ports:
      - "9080:9080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:9080
      Aspire__MongoDB__Driver__ConnectionString: mongodb://admin:password@mongodb:27017/testdb?authSource=admin
      Aspire__StackExchange__Redis__ConnectionString: redis:6379
      Aspire__NATS__Net__ConnectionString: nats://nats:4222
    depends_on:
      - mongodb
      - redis
      - nats

volumes:
  mongodb_data:
  redis_data: