apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mongodb
  namespace: databases
spec:
  interval: 10m
  chart:
    spec:
      chart: mongodb
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      version: ">=13.0.0"
  install:
    crds: Create
  upgrade:
    crds: Create
  values:
    architecture: replicaset
    replicaSet:
      enabled: true
      name: rs0
      replicas: 3
    auth:
      enabled: true
      username: admin
      password: mongopassword
    persistence:
      enabled: true
      storageClass: longhorn
      size: 20Gi