apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nats
  namespace: databases
spec:
  interval: 10m
  chart:
    spec:
      chart: nats
      sourceRef:
        kind: HelmRepository
        name: nats
        namespace: flux-system
      version: ">=0.19.0"
  values:
    nats:
      image: nats:latest
    auth:
      basic:
        users:
          - username: admin
            password: natspassword
    cluster:
      enabled: true
      replicas: 3
    persistence:
      enabled: true
      storageClass: longhorn
      size: 5Gi
