# helm/serviceexample/values.yaml

# Application Configuration
replicaCount: 3

image:
  repository: serviceexample  # Local image or your registry
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 9080  # Match your app port
  targetPort: 9080

# Resource Management
resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

# Auto-scaling
autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70

# Environment Variables
env:
  ASPNETCORE_ENVIRONMENT: Production
  ASPNETCORE_URLS: http://+:9080
  LOG_LEVEL: Information

# Health check endpoints (match your app)
healthcheck:
  enabled: true
  liveness:
    path: /health
    initialDelaySeconds: 15
    periodSeconds: 10
  readiness:
    path: /ready
    initialDelaySeconds: 10
    periodSeconds: 5

# Database and cache connections (optional for Helm)
mongodb:
  enabled: false
redis:
  enabled: false
nats:
  enabled: false