apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  interval: 10m
  chart:
    spec:
      chart: loki-stack
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      version: ">=2.9.0"
  install:
    createNamespace: true
  values:
    loki:
      persistence:
        enabled: true
        storageClassName: longhorn
        size: 10Gi
